# Generated by Django 3.2.5 on 2021-09-29 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20210811_0340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='user',
        ),
    ]
